### ISSUE TITLE
Rust lang quick install link using curl ...

### ISSUE THREAD

**Issue by metacritical** [rust-lang/rust-www#100]
The easiest way to install rust is through the install page here 

[rust-lang.org/install](http://www.rust-lang.org/install.html)

the command given is :

``` bash
curl -s https://static.rust-lang.org/rustup.sh | sudo sh
```

Instead can we not have the link like this :

``` bash
curl -s https://get.rust-lang.org | sudo sh
```

such a link is easier to remember at the top of the head and most people wont have to visit the site  just to get the install link.

Thanks.

**Comment by AndrewBrinker** [comment]
With the new rustup.rs install instructions the link is pretty short. That being said, I don't know that the link being memorable matters that much.

**Comment by davidalber** [comment]
The current command on the homepage is
```sh
curl https://sh.rustup.rs -sSf | sh
```

That's possibly what it was at the time of the previous comment. This command both satisfies the original intention of the ticket and is shorter than the suggestion. I humbly suggest that we can close the issue.

**Comment by steveklabnik** [comment]
Agreed!
