### ISSUE TITLE
Sources on download page appears not to be updated

### ISSUE THREAD

**Issue by jan-hudec** [rust-lang/rust-www#101]
I've downloaded the sources from the link as published on install page, https://static.rust-lang.org/dist/rustc-nightly-src.tar.gz, but the sources there appear to be outdated. I couldn't quickly find a way to check which exact version it is, but the extracted archive still contains `old_io` under the `io` name for example.

**Comment by AndrewBrinker** [comment]
This appears not to be an issue anymore.

**Comment by jan-hudec** [comment]
Appears not.
