### ISSUE TITLE
https://rust-lang.org/ doesn't redirect

### ISSUE THREAD

**Issue by vmx** [rust-lang/rust-www#1019]
I'm not sure if this is the right repository, if not, please let me know where else I should file it.

http://rust-lang.org/ redirects to https://www.rust-lang.org/
https://rust-lang.org/ gives an error

```
$ curl 'http://rust-lang.org' -I
HTTP/1.1 302 Found
Date: Wed, 24 Jan 2018 16:19:22 GMT
Server: Apache
Location: https://www.rust-lang.org
Content-Type: text/html; charset=UTF-8

$ curl 'https://rust-lang.org' -I
curl: (7) Failed to connect to rust-lang.org port 443: Connection refused
```

I'd expect http://rust-lang.org/ to redirect to https://www.rust-lang.org/.

**Comment by steveklabnik** [comment]
@rust-lang/infra

**Comment by simeg** [comment]
Duplicate of #955.

**Comment by aidanhs** [comment]
Closing as duplicate. Thanks for the report!
