### ISSUE TITLE
make rustbyexample more prominent

### ISSUE THREAD

**Issue by mdinger** [rust-lang/rust-www#103]
This is a clone of https://github.com/rust-lang/rust-by-example/issues/509

> The site rustbyexample.com should be much more visible on the main rust-lang.org site. Currently there's only an obscure link deep down in All docs -> External documentation. I've read The Book several times over the past months and never even realized that rustbyexample.com existed.
> 
> I think it's an excellent companion resource and should be listed prominently next to The Book.
> 
> Since the same authors are maintaining it all anyway this shouldn't be a problem :)

cc @sstirlin

**Comment by mdinger** [comment]
As seen in https://github.com/rust-lang/rust-www/issues/71, they're weren't sure where to put it on the webpage so they put it at the bottom.

One solution would be to make *All docs* the go to page from rust-lang and remove the rest. I doubt that would be popular so I'm not sure what else could be done besides drop downs, expanding the table, or dropping other resources. Maybe drop the reference. Surely, someone examining Rust for the first time would get more out of the Book and rustbyexample than the reference. I doubt dropping the reference would be popular either though.

**Comment by sstirlin** [comment]
I think it's crucial to snag new recruits.  The Reference and API are only useful after both the Book and rustbyexample.com have been worked through.  I suggest even more drastic changes, like this:

Getting Started   <--- the 30-minute tutorial
Book   <---  trpl
Examples  <---  rust by example 
Full docs  <--- a separate page
        Getting Started
        Book
        Examples
        Reference
        API
        IRC and other stuff

**Comment by sstirlin** [comment]
Ugghhh... in my previous comment I mean for everything below "Full docs" to be on the separate Full docs page

**Comment by davidalber** [comment]
It seems like the request (or at least the spirit of it) was implemented at some point. I don't know what the page looked like three years ago, but here's the situation now:
- A link to https://rustbyexample.com/ appears below the example on https://www.rust-lang.org/.
- A link to https://rustbyexample.com/ appears second in the "Learning Rust" section of the [documentation page](https://www.rust-lang.org/documentation.html).

That seems to be an improvement over "an obscure link deep". Is there more you think should be improved here or is this now closable?

**Comment by sstirlin** [comment]
Seems good to me.  I've long forgotten about this, so close it.  Thanks

**Comment by steveklabnik** [comment]
not only all of that, but we're actually moving RBE into doc.rust-lang.org!

I think at this point we can close this.
