### ISSUE TITLE
New Website Logo: Aprila Bank

### ISSUE THREAD

**Issue by israrkhan** [rust-lang/rust-www#1053]
- Organization name: Aprila Bank
- Homepage url: https://www.aprila.no 
- Logo url: https://aprila.no/_nuxt/img/logo-type.90f86e9.svg
- How you are using Rust: Orchestrating business process flows for onboarding, KYC, credit decisions and more.
- Url describing Rust usage: N/A
- Organization contact:  Israr Khan, CDO Aprila Bank, israr@aprila.no 

Our team has open sourced some smaller parts of our setup, and eventually we will open source more: https://github.com/aprilabank

**Comment by Deedasmi** [comment]
Hi @israrkhan, your logo link 404s. Has it been moved?

**Comment by israrkhan** [comment]
Yes indeed, we've gone out of Beta and officially launched. 
Updated it now. 
https://aprila.no/_nuxt/img/logo-type.90f86e9.svg
