### ISSUE TITLE
Invalid value for version

### ISSUE THREAD

**Issue by whipsch** [rust-lang/rust-www#107]
The editor tries to make requests to the playpen using the version string 'master'.  The current playpen only accepts 'beta' and 'nightly'.

[Here](https://github.com/rust-lang/rust-www/blob/0443e47f0d1353a4b5d552a0475db0f356792264/_includes/editor.js#L79)

Not sure if we should be using beta or nightly.

**Comment by brson** [comment]
Let's use beta.
