### ISSUE TITLE
Source code link for rustc 1.25.0 is incorrect

### ISSUE THREAD

**Issue by saintdev** [rust-lang/rust-www#1078]
The links for the source code for rustc 1.25.0 at the bottom of https://www.rust-lang.org/en-US/other-installers.html point to the wrong place https://static.rust-lang.org/dist/rustc-1.25-src.tar.gz instead of https://static.rust-lang.org/dist/rustc-1.25.0-src.tar.gz

**Comment by phansch** [comment]
Looks like this was fixed with https://github.com/rust-lang/rust-www/pull/1079
