### ISSUE TITLE
New Website Logo: Tonsser

### ISSUE THREAD

**Issue by davidpdrsn** [rust-lang/rust-www#1083]
- Organization name: Tonsser
- Homepage url: https://tonsser.com
- Logo url: https://www.dropbox.com/s/9kxo25glfzol3ju/Tonsser_Large_BLK.png?dl=1
- How you are using Rust: Moving performance sensitive parts of our Ruby on Rails API to Rust for more speed and higher reliability.
- Url describing Rust usage: `None`
- Organization contact: David Pedersen david.pdrsn@gmail.com

**Comment by Deedasmi** [comment]
This issue can be closed.
