### ISSUE TITLE
Current 404 page is the generic GitHub Pages one

### ISSUE THREAD

**Issue by ericsampson** [rust-lang/rust-www#109]
I followed a malformed link to one of the pages on github.com/rust-lang and noticed that it appears the current 404 page is the generic one supplied by Pages, whose text is aimed more at the site owners than visitors. It would be fun to have a fun/useful custom Rust 404 page, unfortunately I'm not a web dev and so can't help with this, but I thought I'd point it out FWIW.

**Comment by edunham** [comment]
https://www.rust-lang.org/there-is-no-page-here

Accidentally fixed it as part of the HTTPS deployment
