### ISSUE TITLE
New Website Logo: Figma

### ISSUE THREAD

**Issue by evanw** [rust-lang/rust-www#1097]
- Organization name: Figma
- Homepage url: https://www.figma.com/
- Logo url: https://gist.github.com/evanw/40705d7854dcc6de5b9fed905eebc5c9
- How you are using Rust: Our real-time multiplayer syncing server (used to edit all Figma documents) is written in Rust.
- Url describing Rust usage: https://blog.figma.com/rust-in-production-at-figma-e10a0ec31929
- Organization contact: Evan Wallace (evan@figma.com)

**Comment by Deedasmi** [comment]
Just a ping that this has been corrected. Sorry about the mistake!
