### ISSUE TITLE
When choosing to read the Book, focus .page-wrapper so users can scroll using keyboard

### ISSUE THREAD

**Issue by mitchhentges** [rust-lang/rust-www#111]
When I choose to read "The Rust Programming Language" book, the page doesn't let me scroll by arrow keys. I have to manually click on the main content (the non Table of Contents area) in order to make scroll-by-keyboard work.

__To reproduce:__
1. Go to homepage
2. Click Docs(Beta) -> Book
3. Try and navigate the page using the arrow keys on the keyboard
(The user needs to manually click on the content before scrolling by kb works)

**Comment by CalMlynarczyk** [comment]
Is this applicable anymore with the new books UI? I'm not able to reproduce this as of the latest.

**Comment by mitchhentges** [comment]
Looks good :+1:
