### ISSUE TITLE
World map of Rust contributors

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust-www#115]
So I was thinking it'd be neat to have [a map of people who'd contributed](https://github.com/jakub-/github-contributors-geojson/blob/master/rust.geojson) to Rust on the website. What do people think?

I generated it from the GitHub profile information for the contributors of `rust-lang/rust` but perhaps it'd be more appropriate to do it for all repositories under the organisation.

In any case, seems to me like a nice way of showcasing our global community?

cc @brson

**Comment by bombless** [comment]
That would certainly be wonderful!
So I guess only for those who filled location field for their Github account will contribute to this geolocation database, is that right?

**Comment by jakub-** [comment]
@bombless Correct! The script that generated the map is [here](https://github.com/jakub-/github-contributors-geojson/blob/master/export_github_contributors_as_geojson.rb).

**Comment by jakub-** [comment]
I regenerated the map with contributors to all repositories under `rust-lang`, a few more people in the crowd!

**Comment by jakub-** [comment]
Oh, @steveklabnik, maybe you have thoughts on this?

**Comment by steveklabnik** [comment]
It might be neat, yeah :) I'm not sure where it fits in with the current site, exactly

**Comment by bombless** [comment]
Maybe put a clickable icon around the "fork me on github" icon.
Or just put it to the bottom of the homepage, with text like "who created Rust" or something.

**Comment by kenshinji** [comment]
WOW, this is AWESOME!! I am going to join the community of Rust contributors.

**Comment by edunham** [comment]
The GitHub account that hosted the rust.geojson linked above has been deleted. Options to fix this issue: 

* Dig the source for rust.geojson out of archive.org and host it elsewhere
* Find an equivalent tool hosted by someone else
* Close as won't/can't fix

Thoughts?

**Comment by AndrewBrinker** [comment]
I don't know that this is really necessary, and given that the relevant GitHub account is gone, it's probably not worth the effort to re-do. If at some point a third party wants to put something like this up they should feel free, but I don't think it should be added to the site.

**Comment by steveklabnik** [comment]
Same.
