### ISSUE TITLE
Broken “move semantics” link in README

### ISSUE THREAD

**Issue by ddfreyne** [rust-lang/rust-www#127]
[README.html](http://doc.rust-lang.org/book/README.html) has a link to [move-semantics.html](http://doc.rust-lang.org/book/move-semantics.html), which is a 404:

> Rust has [move semantics](http://doc.rust-lang.org/book/move-semantics.html) by default, so if we want to make a copy of some data, we call the clone() method. [..]

**Comment by alexcrichton** [comment]
Thanks for the heads up! For now this has been [fixed on master](http://doc.rust-lang.org/nightly/book/README.html) and we'll see what we can do about backporting.
