### ISSUE TITLE
[docs] Exclude 0.11 docs from search engines

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust-www#128]
When googling for "c_int" (and many other rust doc queries) no. 1 result in Google is doc.rust-lang.org/0.11.0/libc/types/os/arch/c95/type.c_int.html

Since 0.11 docs are ancient and more likely to be misleading than useful I suggest excluding them from search engines.

**Comment by alexcrichton** [comment]
Good suggestion! I've added these all to robots.txt to disallow, so they should be on their way out now!
