### ISSUE TITLE
Missing documentation for beta

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust-www#135]
There is http://doc.rust-lang.org/stable/ for stable and http://doc.rust-lang.org/nightly/ for nightly.
There is no equivalent for beta. There is http://doc.rust-lang.org/1.0.0-beta/ , but it's outdated now that 1.1.0 beta is available.

**Comment by alexcrichton** [comment]
Oops! Had to update some nginx rules, but this is now in place, thanks for the report!
