### ISSUE TITLE
Incorrect download links for beta MSI files.

### ISSUE THREAD

**Issue by gentoo90** [rust-lang/rust-www#136]
No version in links, while files in `https://static.rust-lang.org/dist/` have it:
`https://static.rust-lang.org/dist/rust-beta-i686-pc-windows-gnu.msi` instead of `https://static.rust-lang.org/dist/rust-1.1.0-beta-i686-pc-windows-gnu.msi`
`https://static.rust-lang.org/dist/rust-beta-x86_64-pc-windows-gnu.msi` instead of `https://static.rust-lang.org/dist/rust-1.1.0-beta-x86_64-pc-windows-gnu.msi`

BTW, will all new betas be without version in their names (like nightlies) from now on?

**Comment by steveklabnik** [comment]
> BTW, will all new betas be without version in their names (like nightlies) from now on?

Yes.

**Comment by brson** [comment]
Fixed.
