### ISSUE TITLE
Host //rust-lang.org over HTTPS

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust-www#144]
It is possible to host a GitHub Pages hosted website that has a custom domain over HTTPS. I did this for [my website](https://rwell.org) using [this tutorial](https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/) and it didn't take too long.

I asked about this a few minutes ago on IRC and @steveklabnik basically just said it hasn't been done yet, which is fine. I didn't see an existing issue open for this so if allowing HTTPS is something that is planned, then I figure it might be good to open a GitHub Issue to track the progress.

**Comment by frewsxcv** [comment]
It looks like https://github.com/rust-lang/rust/issues/13180 is also open (which I apparently also commented in a few months ago) so if that's a better place for discussion, this can be closed

**Comment by alexcrichton** [comment]
I agree that https://github.com/rust-lang/rust/issues/13180 is where discussion on this should be happening, so closing in favor of that, but thanks for the report!
