### ISSUE TITLE
FFI Section of Book References std::comm

### ISSUE THREAD

**Issue by BrodyHolden** [rust-lang/rust-www#151]
The FFI section of the book (https://doc.rust-lang.org/nightly/book/ffi.html#asynchronous-callbacks) references std::comm. I suspect this reference should be replaced with one to std::sync::mpsc (https://doc.rust-lang.org/std/sync/mpsc/).

**Comment by steveklabnik** [comment]
Could you move this issue to rust-lang/rust please? Thanks!
