### ISSUE TITLE
Where is the security mailing list?

### ISSUE THREAD

**Issue by mcast** [rust-lang/rust-www#156]
(I don't have an issue to report)

https://github.com/rust-lang/rust-www/blob/60c1a1dd37fc173e09459f40dc3b20af29db5b5b/security.html#L70-L72
http://www.rust-lang.org/security.html
> Receiving Security Updates
>
> The best way to receive all the security announcements is to subscribe to the Rust security mailing list. The mailing list is very low traffic, and it receives the public notifications the moment the embargo is lifted.

I couldn't find it from the website.
* If there is still a list, could you add a hyperlink please?
* For the curious surfer looking for old security issues, could you point to them please?

I found the [internals thread](https://internals.rust-lang.org/t/proposed-security-disclosure-policy/2024) and [the issue tag](https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=label%3AA-security).  The thread mentions a bug that doesn't have the tag, so the security archaeologists will have extra searching to do.

**Comment by steveklabnik** [comment]
We haven't gotten it up yet due to an argument over hosting our own vs Google groups.

**Comment by edunham** [comment]
@brson, @steveklabnik I propose setting up rust-security-announce@googlegroups.com for this purpose, as discussed in today's meeting.

As discussed in the meeting, we're choosing Google Groups because the time required for maintaining an email server could be better spent elsewhere (so Mailman's not a good fit), and announce-only (so Discourse is not a good fit).

**Comment by edunham** [comment]
@steveklabnik just fixed this in https://github.com/rust-lang/rust-www/pull/188

@mcast, the Google Groups list is configured to have a public archive of messages, which will over time become the resource of old issues which you mentioned wanting as well.
