### ISSUE TITLE
Link to Jakub's github 404's

### ISSUE THREAD

**Issue by edunham** [rust-lang/rust-www#162]
https://github.com/jakub- does not appear to be a person, but https://github.com/rust-lang/rust-www/blob/master/team.md thinks it is.

**Comment by steveklabnik** [comment]
They probably just deleted their GitHub account. I would just not look into it further.

**Comment by edunham** [comment]
@steveklabnik It bugs me to have a broken link on the page. Is there any way of getting in contact with them to find updated information we should be publishing?

**Comment by steveklabnik** [comment]
I would argue we should just remove the link. People who delete their account do so for a reason, and if they haven't let us know, I'd think it'd be bad to try to hunt them down or something.

**Comment by edunham** [comment]
Remove the link and leave his name, or remove all reference to him? I was under the impression that being listed as part of a team was partly to enable community members to get in touch if they have questions, and posting someone's name with no contact information does not enable that.

If the fix is to remove him from the page entirely, that seems like effectively removing him from the team, and should probably be the decision of the core team (?). 

I guess that the ideal solution would be to document expectations about subteam participation in a way that clarifies what we'll do when an account gets deleted.

**Comment by steveklabnik** [comment]
If he, as a person, has just dropped out of open source and Rust, then he should just be removed from the page. Does anyone in @rust-lang/compiler know if @jakub- is still around under a different name?

**Comment by nikomatsakis** [comment]
I've heard nothing from him, I'm inclined to just remove the link for the time being.

**Comment by edunham** [comment]
At Niko's recommendation on IRC, I took the policy questions over to [internals](https://internals.rust-lang.org/t/subteams-rfc-ambiguity-how-is-membership-determined/2481). It also explains why I don't think "just delete the link" is a viable solution.

**Comment by Diggsey** [comment]
Based on some googling, he seems to have also deleted his twitter and secondary github account, as well as possibly invoking the "right to be forgotten", although that could have been for someone else with the same name.

**Comment by edunham** [comment]
Talked to @aturon about this and he suggested emailing Jakub directly to ask what he'd prefer. I pulled 2 email addresses from the Git history and sent them a note checking in and asking what he'd like us to do about the broken link. I'll update this ticket if I hear back from the one that didn't bounce.

**Comment by edunham** [comment]
Jakub replied to my email and indicated that his profile should be removed from the compiler team page. PR incoming.
