### ISSUE TITLE
& in colored method signatures not rendered correctly on chrome in windows 10

### ISSUE THREAD

**Issue by mschwaig** [rust-lang/rust-www#168]
When rendering [the documentation to any standard library class](https://doc.rust-lang.org/std/collections/struct.LinkedList.html) with Chrome Version 44.0.2403.130 m (64-bit) - the latest release on Windows 10, the & character is obviously not rendered correctly, as demonstrated by [this picture](http://imgur.com/RsVvnJg).

Is there any more information I can provide to help fix this issue?

EDIT: I could also reproduce the issue with the same version of Chrome on Windows 8.1

**Comment by steveklabnik** [comment]
(the original was actually the correct place)
