### ISSUE TITLE
Port http://www.ncameron.org/rust.html to RLO

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust-www#171]
Having a page we can point to for new contributors to the Rust ecosystem (and not just the Rust source code) would be valuable.

Once ported, additions could be made about educational and social organization contributions that are useful too.

**Comment by edunham** [comment]
Thanks for the feedback! We're currently working on an [overhaul of the website design](https://internals.rust-lang.org/t/rusty-web-improvement-bureau/2572) to put the information people need where it's most useful to them.

**Comment by edunham** [comment]
because it's a subset of #177
