### ISSUE TITLE
Add Apache and MIT license texts? 

### ISSUE THREAD

**Issue by edunham** [rust-lang/rust-www#174]
Probably same as https://github.com/rust-lang/regex . They're referred to by the COPYRIGHT file but not provided in this repo

re: https://github.com/rust-lang/rust/issues/25664

**Comment by brson** [comment]
Yes. Furthermore, the COPYRIGHT file in this repo looks totally bogus to me. It's an ancient clone of the Rust COPYRIGHT file, probably added with the intent of placing the *Rust* copyright somewhere stable, *not* as the license for this repo. Still - I think we should assume this repo is MIT/ASL2 and fix the license.
