### ISSUE TITLE
RWIB Mission 2: Community Page

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-www#176]
[Link](https://internals.rust-lang.org/t/rusty-web-improvement-bureau/2572/1#community-page).

Today the navbar is overrun by 'community' links, but still there is more
info to disseminate. Create a new page, to be linked from a single new
'Community' navbar link. This page needs to be a friendly and
accessible intro to the world of Rust.

Subjects covered should include:

* The importance of the COC (with link) and diversity
* Team structure (with link)
* The community and moderation teams in particular
* The RFC process, with link to RFC readme
* Subteam reports and TWiR
* Forums, IRC and other communication venues
* It should explicitly explain how to get help
* Calendar. Try to embed a combination of the event calendar and the release calendar.
* List of meetup groups
* blog
* twitter

Think about how to organize this by audience. Some community members
are devs and some are users. Consider that the primary audience for
this page is mostly users, for the contributing page is mostly devs.

Come up with a design that conveys all of this information, either
directly or through additional links, without being overwhelming. This
will be one of the most important newbie resources.

I'm most worried here about conveying a dedication to diversity, as we
don't have a lot of existing material to crib off of, there's overlap
with the CoC, and anything we say needs to be worded artfully.

Adapt material from [the current
docs](file:///home/brian/dev/rust2/build/doc/index.html#community-&-getting-help).

**Comment by edunham** [comment]
#117 re: the calendar point in the list above.

**Comment by efindlay** [comment]
I'd like to take on Mission 2.

**Comment by brson** [comment]
@efindlay You got it! Keep be updated on your progress!
