### ISSUE TITLE
RWIB Mission 3: Contributing Page

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-www#177]
[Link](https://internals.rust-lang.org/t/rusty-web-improvement-bureau/2572/1#contributing-page).

Create a contributing page that adapts [nrc's stuff](http://www.ncameron.org/rust.html)
and [CONTRIBUTING.md](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md).

It should be simple and accessible, with consideration for non-coding contributions.

* It should have a link to instructions on submitting bug reports.
* It should lead people to instructions for getting involved in RFC process.
* It should provide leads for getting involved in evangelism.

It might highlight major initiatives, like IDE's. Such initiatives would need
stable landing pages to link to, like internals threads or GitHub issues.

Cross-link with CONTRIBUTING.md.

[Scala's page](http://scala-lang.org/contribute/) is good to crib off of.

**Comment by Havvy** [comment]
So, should issue #117 be closed since this subsumes it?

**Comment by brson** [comment]
@sirDonQui is going to take a shot at this.

**Comment by brson** [comment]
@efindlay has a an implementation in his [community PR](https://github.com/rust-lang/rust-www/pull/193).

**Comment by brson** [comment]
@nrc has created [a page for his ide initiative](https://github.com/rust-lang/rust-www/pull/195). Right now it's not hooked into anything and needs to be reworked to integrate into the site.

Part of this task is to surface the major project initatives so his work needs to be connected to it. I'm not sure the final form though. Original vague intent was to do something like [scala's contributing page](http://scala-lang.org/contribute/), listing some major contribution areas with further links.

**Comment by brson** [comment]
Done.
