### ISSUE TITLE
RWIB Mission 5: Documentation Page

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-www#179]
[Link](https://internals.rust-lang.org/t/rusty-web-improvement-bureau/2572/1#documentation-page).

Today, [the documentation landing
page](http://doc.rust-lang.org/nightly/) lives in the Rust tree, and
is generated for each release channel. As Rust grows though, more
documentation lives out of tree and needs to be discoverable.

Let's reorganize this so that the website itself is the main landing
page for finding docs.

Start by moving the contents of the existing documentation index into
rust-www, reducing the existing doc index to links to the in-tree
docs, as well as a link to the website for more information.

Add a link to the new website-based [FAQ](#faq).

Brainstorm about other documentation we might want to link to and what
standards of quality and stability we might require before officially
endorsing them.

**Comment by efindlay** [comment]
I would like to take this on after #193.

**Comment by brson** [comment]
@efindlay You got it! Thanks!

**Comment by efindlay** [comment]
It looks like my first step should just be a pure refactor with no visible changes (except for URL). I'm guessing the tricky part will be finding and changing links to the current documentation landing page.

**Comment by efindlay** [comment]
Set of possible links:

https://doc.rust-lang.org
https://doc.rust-lang.org/
https://doc.rust-lang.org/index.html
https://doc.rust-lang.org/nightly
https://doc.rust-lang.org/nightly/
https://doc.rust-lang.org/nightly/index.html
https://doc.rust-lang.org/stable
https://doc.rust-lang.org/stable/
https://doc.rust-lang.org/stable/index.html

**Comment by efindlay** [comment]
Grepped with,

git grep -En 'doc.rust-lang.org[^/]'
git grep -En 'doc.rust-lang.org/[^a-z]'
git grep -En 'doc.rust-lang.org/index.html'
git grep -En 'doc.rust-lang.org/nightly[^/]'
git grep -En 'doc.rust-lang.org/nightly/[^a-z]'
git grep -En 'doc.rust-lang.org/nightly/index.html'
git grep -En 'doc.rust-lang.org/stable[^/]'
git grep -En 'doc.rust-lang.org/stable/[^a-z]'
git grep -En 'doc.rust-lang.org/stable/index.html'

**Comment by efindlay** [comment]
Oh. Only links were part of #![doc ... html_root_url = https://doc.rust-lang.org/nightly/ which doesn't need to change, does it?

**Comment by brson** [comment]
This is done.
