### ISSUE TITLE
Rust's short description on the home page is a bit weird.

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust-www#191]
>Rust is a systems programming language that runs blazingly fast, prevents nearly all segfaults, and guarantees thread safety. 

I think this should say that it prevents all segfaults – otherwise it's inconsistent with the last part, that it guarantees thread safety. You can break both invariants by using `unsafe`. The other possibility would be to phrase it like "prevents nearly all segfaults and almost guarantees thread safety".

Also, shouldn't it say data-race freedom instead of thread safety?

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/issues/26215 is open re "thread safety"
