### ISSUE TITLE
Enable syntax highlighting for faq

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-www#246]
The new FAQ has a bunch of Rust code that isn't highlighted.

**Comment by azerupi** [comment]
Are you guys already using a library for that?
I use [highlight.js](https://highlightjs.org/) for mdBook and it works well.

**Comment by steveklabnik** [comment]
It's rendered server-side, Jekyll does it.

**Comment by azerupi** [comment]
Is it just a matter of replacing triple back ticks with the tags below?

```
{% highlight rust %}

{% endhighlight %}
```

**Comment by azerupi** [comment]
I have investigated the html output and code blocks are rendered with the correct html for styling:

```html
<pre><code class="language-rust" data-lang="rust"><span class="k">fn</span> <span class="n">is_odd</span><span class="p">(</span><span class="n">x</span><span class="o">:</span> <span class="kt">i64</span><span class="p">)</span> <span class="o">-&gt;</span> <span class="kt">bool</span> <span class="p">{</span>
    <span class="k">if</span> <span class="n">x</span> <span class="o">%</span> <span class="mi">2</span> <span class="o">!=</span> <span class="mi">0</span> <span class="p">{</span> <span class="k">true</span> <span class="p">}</span> <span class="k">else</span> <span class="p">{</span> <span class="kc">false</span> <span class="p">}</span>
<span class="p">}</span>
</code></pre>
```

So it's highly probable that the only problem is a missing stylesheet.

**Comment by brson** [comment]
@azerupi Great! Will you submit a PR?

**Comment by azerupi** [comment]
Well I can't test it locally, so I can't really pinpoint the specific problem. But I know for sure that it's a missing css file. I will try to take a look, but if someone else can beat me to it, please do :)
