### ISSUE TITLE
Modify downloads.md to use the default template

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-www#247]
After the [next update](https://github.com/rust-lang/rust-www/pull/244) most every page on the website has a consist style with a horizontal rule and page title following the header. Except the download page, which has a very customized style. It looks weird to me when I'm clicking between pages.

**Comment by fredericmarx** [comment]
I built a possible fix for this at https://github.com/fredericmarx/rust-www/commit/7ca5d95acc1c9754964a8a755a91f19cae540372.

Feel free to comment.

<img width="981" alt="screen shot 2016-03-30 at 02 37 55" src="https://cloud.githubusercontent.com/assets/954294/14128850/ef303648-f624-11e5-9328-e7da66d017b6.png">

**Comment by brson** [comment]
@fredericmarx Sorry I missed your comments here. The screenshot looks good to me, except that for some reason the "Downloads" header feels out of place to me. I'm not sure if it's just because I'm so used to the page without the header or not. It seems like doesn't fit into the page as well as the others, where on the other pages the header is immediately followed be some sort of summary text.

Perhaps I would get used to it. @steveklabnik what do you think of that screen?

**Comment by steveklabnik** [comment]
I feel _exactly_ the same. I'm tempted to merge it though, as I don't really dislike it, I'm just not sure if I like it, which is a subtle difference.

**Comment by fredericmarx** [comment]
Ha, no worries, I also only just realised you had replied.

Any news on this? I figured as most pages had a header it would be a good idea to have one here, too, for consistency's sake. I don't have a strong opinion against leaving it out though either.

**Comment by steveklabnik** [comment]
I think I vote merge. @brson ?

**Comment by brson** [comment]
Yes let's do it @fredericmarx
