### ISSUE TITLE
www.rust-lang.org never seems to return 404

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust-www#261]
For broken URLs like https://www.rust-lang.org/fail it returns 200 OK with the contents of error.html, it should return 404. This causes issues with search engines etc. for example: https://duckduckgo.com/?q=site%3Awww.rust-lang.org+%22internal+website+error%22 shows a few dead links.

**Comment by alexcrichton** [comment]
cc @edunham

**Comment by edunham** [comment]
Oops, thanks for catching that -- I accidentally left the 200 default where I shouldn't have when I set up the cloudfront distribution. I've fixed the settings to pass the error code through, but the changes might take a couple hours to propagate.
