### ISSUE TITLE
Gender Identity & Expression in the Code of Conduct

### ISSUE THREAD

**Issue by Charlotteis** [rust-lang/rust-www#268]
I just filled in an issue over in Node.js about including 'gender identity and expression' into their Code of Conduct: https://github.com/nodejs/inclusivity/issues/82. I know that Node effectively adopted the Rust CoC so I thought I should come over here and suggest the same thing, as I am very interested in learning Rust, too!

I am proposing that we include 'gender identity and expression' in the Code of Conduct used for all of Rust. I've managed to include this in the Codes of Conducts for several event and online communities of a smaller nature, so I'm hopeful that people seem to be receptive to the idea.

Solely referring to 'gender' does not recognise the [non-binary](http://gender.wikia.com/wiki/Non-binary) or [agender](http://gender.wikia.com/wiki/Agender) folk. (As often, 'gender' is widely regarded as the popular idea of man/woman). Gender identity feels like a clearer and more inclusive term.

I realise the CoC says 'similar personal characteristic', but it feels like it'd be good to have things explicitly said rather than assumed. The [Contributor Covenant](http://contributor-covenant.org/) has a lot of really useful things in it too (like age, technology choices, lack of religion), which we could consider co-opting things from.

I hope I explained myself well, and I'm happy to answer any questions.
Thanks so much for reading!

**Comment by steveklabnik** [comment]
:+1: from me

/cc @rust-lang/core @rust-lang/moderation

**Comment by steveklabnik** [comment]
@Charlotteis would you like to send a PR for this change, or should I handle it? https://github.com/rust-lang/rust-www/blob/master/conduct.md is the file that would need the change.

**Comment by aturon** [comment]
I'm :+1: as well, this is clearly within the spirit and intent of the original CoC, and I have no objection to spelling it out more explicitly.

**Comment by nikomatsakis** [comment]
:+1:

**Comment by BurntSushi** [comment]
:+1:

**Comment by Manishearth** [comment]
:+1: 

@steveklabnik The COC isn't explicitly anyone's responsibility afaict. The mod team is responsible for *interpreting* it but not modifying it. Then again, this is sort of a matter of making explicit something which most of us probably interpreted anyway. It also has a feel of being something that would belong under the community subteam. But "officially" I think this defaults to core ...?

Not that the precise governance matters much here :smile:

**Comment by aturon** [comment]
Yeah, this is definitely core team purview, with input from mods and community.

**Comment by Charlotteis** [comment]
@steveklabnik I took a shot at making a PR.

It's really encouraging to see so many +1's thank you all. Happy to answer any questions / discuss this as much is needed!

**Comment by huonw** [comment]
:+1: from me too: makes total sense to make the wording match the intention.

**Comment by mbrubeck** [comment]
+1

**Comment by niconii** [comment]
:+1:
