### ISSUE TITLE
FAQ index entries are missing numbers past 7 on chrome

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-www#275]
[screenshot](http://imgur.com/4JOGStq).

[Thread](https://www.reddit.com/r/rust/comments/40zxey/major_website_updates/cyz6qkr).

Chrome 47.0.2526.83 on Android 6.0.1 and Chrome on Windows.

**Comment by brson** [comment]
cc @AndrewBrinker do you mind looking at this?

**Comment by AndrewBrinker** [comment]
Yeah, I saw this. It's unusual. I'll see if I can replicate it.

**Comment by AndrewBrinker** [comment]
Looks like this is a known bug: http://caniuse.com/#search=column (known issue number 6).

**Comment by AndrewBrinker** [comment]
I'm working on a fix now. I'll submit a PR as soon as it's working.

**Comment by AndrewBrinker** [comment]
Okay. Pull request made: https://github.com/rust-lang/rust-www/pull/278

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/rust-www/pull/278
