### ISSUE TITLE
Provide some context for the terminology used when describing HKTs

### ISSUE THREAD

**Issue by boblehest** [rust-lang/rust-www#284]
When reading the [FAQ entry about HKTs](https://github.com/rust-lang/rust-www/blob/master/faq.md#what-are-higher-kinded-types), I'd like to know where the terminology stems from.

Example: 

> Any complete type, like i32, bool, or char is of kind *.
> A type with one parameter, like Vec<T> is of kind * -> *

Does this stem from another language? Is it from a mathematics field?

**Comment by AndrewBrinker** [comment]
This is all from the field of type theory. The notation is included as I felt it provides a clearer picture of what higher-kinded types are. They are, in essence, "types with holes". That is, they have unfilled type parameters. The notation is designed to show both the relationship between the number of unfilled parameters and the type's "kindedness" as well as hint at the dual nature of a higher-minded type as both a type itself and as a function that returns another type, possibly also with holes.

From a logic perspective, kinds are "one level up" from types. That is, they are similar to the simply-typed lambda calculus, with the type `*` (called "type") which I call a "complete type" (type without holes/unfilled parameters) in the answer.

This answer was one of the toughest to write, and I'm happy to take another crack at clarifying it.

**Comment by boblehest** [comment]
I think the answer is well written, I just think it would be pertinent to tell the readers what branch of mathematics they're currently exploring, in case they want to read more about it. :)

"In type theory, any complete type [..] is denoted by a *", or something like that.

**Comment by brson** [comment]
I believe this is fixed by the most recent changes.
