### ISSUE TITLE
Server's certificate does not match the URL for https://blog.rust-lang.org/

### ISSUE THREAD

**Issue by antond** [rust-lang/rust-www#306]
Google Chrome (the latest version, as of this report) warns that "Server's certificate does not match the URL" while visiting https://blog.rust-lang.org/. It often blocks access to the blog with a Chrome's built-in splash page requiring acceptance to get to the actual Blog page. Once accepted, the page works fine, but the URL bar still indicates a problem with the certificate.

**Comment by steveklabnik** [comment]
that repo is over here https://github.com/rust-lang/blog.rust-lang.org

would you mind re-filing? thanks.

**Comment by antond** [comment]
Thanks for the info. I now see the issue has already been filed [here](https://github.com/rust-lang/blog.rust-lang.org/issues/62), but can't be fixed at this time.
