### ISSUE TITLE
Redirect static.rust-lang.org HTTP -> HTTPS

### ISSUE THREAD

**Issue by Ms2ger** [rust-lang/rust-www#318]
In particular, someone pointed at http://static.rust-lang.org/dist/ for checksums on IRC.

CC @edunham; not sure if this is the right issue tracker.

**Comment by brson** [comment]
I am not sure how do do this. Hopefully it's an option in cloudfront.

**Comment by nagisa** [comment]
See http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/SecureConnections.html.

Namely:

> To require HTTPS between CloudFront and viewers: Configure the Viewer Protocol Policy for some or all of your CloudFront cache behaviors either to redirect HTTP requests to HTTPS requests or to require that viewers use only the HTTPS protocol to access your objects in the CloudFront cache. You can also configure one or more cache behaviors in the same distribution to allow both HTTP and HTTPS, so you can require HTTPS for some objects but not for others.

**Comment by brson** [comment]
I've changed the setting in cloudfront, but so far I don't see it redirecting.

**Comment by brson** [comment]
It's redirecting.
