### ISSUE TITLE
Website renders weird: Chrome on Antergos

### ISSUE THREAD

**Issue by aniketd** [rust-lang/rust-www#323]
![screenshot from 2016-03-17 11-27-32](https://cloud.githubusercontent.com/assets/922486/13837667/98d63590-ec33-11e5-8959-dbe2f74f9b54.png)

**Comment by brson** [comment]
This has sometimes been reported as a problem with old versions of the Fira Sans font. Clearing fonts from your cache could fix it.

**Comment by aniketd** [comment]
@brson That in particular did not fix it. I don't what fixed it. Today I have a completely new setup and it all seems to be fine for a long time. Should this issue be closed then?

**Comment by steveklabnik** [comment]
Yes, let's give this a close. Thanks!
