### ISSUE TITLE
channel-rust-stable.toml.sha256 is missing

### ISSUE THREAD

**Issue by plumenator** [rust-lang/rust-www#335]
The link https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256 which is used by the install script is missing. This also breaks the install instructions given at https://www.rustup.rs

**Comment by alexcrichton** [comment]
Thanks for the report! The standard rustup.sh will just ignore this lookup failure, and otherwise rustup.rs should work just fine (it falls back to an old installer). Did this prevent you from installing Rust, however? That would indeed be a bug!

**Comment by plumenator** [comment]
Rust itself installed fine. However rustup.rs (the replacement of multirust) failed. I guess that would be an issue that should be reported elsewhere.

**Comment by alexcrichton** [comment]
Ah yeah could you open a bug up on https://github.com/rust-lang-nursery/multirust-rs? Thanks!
