### ISSUE TITLE
community.md forgets to mention the actual name of the IRC server

### ISSUE THREAD

**Issue by Arnavion** [rust-lang/rust-www#347]
I vaguely remembered that it was `irc.mozilla.org` or something, and Googled for `rust irc`. The first result was https://www.rust-lang.org/community.html and I could see the names of the channels (`#rust`, `#rust-beginners`) but didn't spot a server name. Ctrl-F for "server" didn't find anything. Eventually I hovered over the mibbit link and spotted the server name in the URL tooltip.

Please place the server name in clear text somewhere on the page :)

**Comment by brson** [comment]
Agreed. Thanks for the suggestion.
