### ISSUE TITLE
New Website Logo: Coturnix

### ISSUE THREAD

**Issue by pijul** [rust-lang/rust-www#352]
- Organization name: Coturnix
- Homepage url: http://www.coturnix.fr
- Logo url: http://www.coturnix.fr/wp-content/uploads/2015/10/Cx-logo-WEB-e1443826117347.png
- How you are using Rust:  machine learning and optimization for minimizing energy consumption in buildings
- Url describing Rust usage: 
- Organization contact: Pierre-Étienne Meunier, pe@coturnix.fr

**Comment by brson** [comment]
Added to the website. Thanks!
