### ISSUE TITLE
New Website Logo: PurchaseClinic.com

### ISSUE THREAD

**Issue by e-oz** [rust-lang/rust-www#354]
> To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: PurchaseClinic.com
- Homepage url: http://purchaseclinic.com/
- Logo url: http://savings.purchaseclinic.com/cart.png
- How you are using Rust: Our backend (REST API) is the 100% Rust server, based on Iron.
- Organization contact: normandiggs@gmail.com . If email with domain purchaseclinic.com is needed, I can create one and send some confirmation email.

**Comment by brson** [comment]
Added to the website. Thanks!
