### ISSUE TITLE
New Website Logo: pingcap/tikv

### ISSUE THREAD

**Issue by ngaut** [rust-lang/rust-www#355]
- Organization name: PingCAP
- Homepage url: https://github.com/pingcap/tikv
- Logo url: https://raw.githubusercontent.com/pingcap/logo/master/pingcap.svg
- How you are using Rust: Building a distributed key-value store with Rust and Raft.
- Url describing Rust usage: 
- Organization contact: liuqi@pingcap.com

**Comment by brson** [comment]
Added to the website. Thanks!
