### ISSUE TITLE
New Website Logo: Ather Energy

### ISSUE THREAD

**Issue by kteza1** [rust-lang/rust-www#357]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: Ather Energy
- Homepage url: www.atherenergy.com
- Logo url: [logo](https://dl.dropboxusercontent.com/u/70321134/a2.png)
- How you are using Rust: Reading bike data published by different subsystems and sending them to the cloud
- Organization contact: Ravi Teja, ravi.teja@atherenergy.com

**Comment by brson** [comment]
Added to the website. Thanks!

**Comment by kteza1** [comment]
Thanks

**Comment by kteza1** [comment]
Can I resubmit this with a different logo?

**Comment by steveklabnik** [comment]
@kteza1 absolutely, open a new issue or send a PR
