### ISSUE TITLE
New Website Logo: 1aim

### ISSUE THREAD

**Issue by yannleretaille** [rust-lang/rust-www#360]
As per @steveklabnik's suggestion.
- Organization name: 1aim
- Homepage url: https://1aim.com
- Logo url: [1aim_logo_png_svg.zip](https://github.com/rust-lang/rust-www/files/245697/1aim_logo_png_svg.zip)
- How you are using Rust: modern, secure and universal access management
- Organization contact: Yann ([my name] at [company name.com])

**Comment by aturon** [comment]
cc @brson

**Comment by brson** [comment]
Thanks @yannleretaille! You're company is up on [the friends page](https://www.rust-lang.org/friends.html) now.
