### ISSUE TITLE
Should there be a Planet Rust?

### ISSUE THREAD

**Issue by AndrewBrinker** [rust-lang/rust-www#368]
A number of programming organizations host a "planet" blog that aggregates content from a variety of other blogs in the organization's community. Would such a thing be desirable for Rust?

This would provide a single easy-to-follow feed for people looking for a variety of quality content from throughout the Rust community, and could also be a decent way to discover new Rust blogs. Best of all, it would involve minimal maintenance on the part of the Rust team, beyond keeping the server up, keeping the aggregation application running, and fielding requests to be added to the list of aggregated blogs.

It looks like the [Planet Feed Reader](http://www.planetplanet.org/) is the standard software for creating this sort of site.

Any thoughts?

**Comment by steveklabnik** [comment]
We've historically talked about it a few times, but many many people replied "what is a planet" even.

**Comment by steveklabnik** [comment]
(Also, I would argue that this is probably better as an internals thread than a bug on the website, visibility-wise)

**Comment by AndrewBrinker** [comment]
Fair point. I've posted it there: https://internals.rust-lang.org/t/should-there-be-a-rust-planet/3434
