### ISSUE TITLE
New Website Logo: AppSignal

### ISSUE THREAD

**Issue by thijsc** [rust-lang/rust-www#374]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: AppSignal
- Homepage url: https://appsignal.com
- Logo url: https://appsignal.com/images/logo@2X.png
- How you are using Rust: Fast and robust monitoring agent for web applications.
- Url describing Rust usage: -
- Organization contact: Thijs Cadier - thijs@appsignal.com

**Comment by brson** [comment]
Added to the page!
