### ISSUE TITLE
New Website Logo: 3DR

### ISSUE THREAD

**Issue by mrpollo** [rust-lang/rust-www#379]
- Organization name: 3DR
- Homepage url: https://3dr.com/
- Logo url: https://dl.dropboxusercontent.com/u/9694286/3dr-logo.svg
- How you are using Rust: Our usage of Rust includes but its not limited to managing accessories connected to our vehicles, Rust handles communications through USB devices to critical components for Flight and our Mobile apps (more details can be provided if needed)
- Organization contact: Ramón Roche @mrpollo

**Comment by brson** [comment]
Thanks! If you don't mind I'd like to condense the description so it fits in the space we have to "Rust handles communications through USB devices to critical components for Flight and our Mobile apps."

**Comment by mrpollo** [comment]
sure thing!
