### ISSUE TITLE
New Website Logo: Ather Energy

### ISSUE THREAD

**Issue by kteza1** [rust-lang/rust-www#383]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: Ather Energy
- Homepage url: https://www.atherenergy.com/
- Logo url: https://dl.dropboxusercontent.com/u/70321134/ather.svg
- How you are using Rust: Sending scooter data to cloud reliably
- Url describing Rust usage: (optional link to e.g. blog post explaining how you use Rust)
- Organization contact: ravi.teja@atherenergy.com

**Comment by kteza1** [comment]
Could you please update the existing entry with this one?

**Comment by steveklabnik** [comment]
Done! :smile:

**Comment by kteza1** [comment]
@steveklabnik Link seems to be broken (Wrong extension I guess. This is svg). Also I updated 'How you are using Rust' section here (thought previous one was bit verbose) :)

**Comment by steveklabnik** [comment]
Oh whoops! I will check again. I thought I did....

**Comment by steveklabnik** [comment]
Fixed. So sorry about that! It hadn't actually deployed when I checked before.

**Comment by kteza1** [comment]
@steveklabnik Awesome. Looks great (though little small). Thank you 😄
