### ISSUE TITLE
New Website Logo: Navitia

### ISSUE THREAD

**Issue by stifoon** [rust-lang/rust-www#387]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: Navitia
- Homepage url: http://www.navitia.io
- Logo url: https://cdn.rawgit.com/CanalTP/navitia/dev/documentation/diagrams/logo_navitia_dark_transparent_bg.svg  
- How you are using Rust: Geocoding service built over Elasticsearch
- Url describing Rust usage: https://github.com/CanalTP/mimirsbrunn 
- Organization contact: marketing.communication@keolis.com

**Comment by steveklabnik** [comment]
PR sent! It should update in a few, once the caches clear. Thanks/welcome! :D

**Comment by steveklabnik** [comment]
It's up!

**Comment by stifoon** [comment]
wow, very quickly ! Tx a lot :)
