### ISSUE TITLE
"Show me!" link on front page goes to http instead of https.

### ISSUE THREAD

**Issue by davidben** [rust-lang/rust-www#390]
On the front page, it says:

> Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety. 
> Show me!

The "Show me!" link goes to http://doc.rust-lang.org/book/README.html, but https://doc.rust-lang.org/book/README.html seems to work just fine.

**Comment by brson** [comment]
Thanks for the report. I'd happily accept a patch.
