### ISSUE TITLE
shksl

### ISSUE THREAD

**Issue by Matrixio** [rust-lang/rust-www#393]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: (as you want it displayed)
- Homepage url: (homepage/primary entry point for users)
- Logo url: (svg if possible, pngs over 400x200px with transparent backgrounds are also acceptable)
- How you are using Rust: (one sentence describing your use of Rust)
- Url describing Rust usage: (optional link to e.g. blog post explaining how you use Rust)
- Organization contact: (name and email. we may contact you when updating this page. alternately you may email this information to user-logos@rust-lang.org and it will be kept secret).

**Comment by steveklabnik** [comment]
Hi there! This is just a copy of the template; did you mean to fill it out?

**Comment by brson** [comment]
Assuming this was submitted accidentally.
