### ISSUE TITLE
New Website Logo: AgilData

### ISSUE THREAD

**Issue by andygrove** [rust-lang/rust-www#398]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: AgilData
- Homepage url: http://www.agildata.com/
- Logo url: http://www.agildata.com/wp-content/uploads/2016/06/AgilData-Logo_1color.svg
- How you are using Rust: MySQL packet capture tool
- Url describing Rust usage: http://www.agildata.com/packet-capturing-mysql-with-rust/
- Organization contact: andy dot grove at agildata dot com

**Comment by brson** [comment]
Hi @andygrove! Thanks for submitting your information for the friends page. The logo link returns a 404 error, and I couldn't find another color logo by browsing around the site. Can you provide a corrected link?

**Comment by andygrove** [comment]
Oops. Here is the correct link.

http://www.agildata.com/img/AgilData-Logo_2color.svg
