### ISSUE TITLE
Add Rust Docs team to website

### ISSUE THREAD

**Issue by AndrewBrinker** [rust-lang/rust-www#405]
I know the Docs Team is just getting going, but it would be nice to have something about it (even if it's just a reference to the IRC channel), so people can find out about it and potentially take part.

It looks like the two changes for adding a team to the site are updating `team.html` with the list of team members, and updating `community.html` with the IRC channel for the team.

**Comment by steveklabnik** [comment]
Since we're not officially a real team yet, I don't think we can do this.

**Comment by AndrewBrinker** [comment]
Even for mentioning the IRC channel? It may make sense to put it into the "Topical Channels" section for now, until things become official.

**Comment by brson** [comment]
Adding it to the channels is good.

**Comment by AndrewBrinker** [comment]
Presumably this can happen if/when [RFCS 1683](https://github.com/rust-lang/rfcs/pull/1683) is merged.

**Comment by AndrewBrinker** [comment]
#474 resolves this issue!
