### ISSUE TITLE
redirect doc.rust-lang.org?

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust-www#415]
1: https://doc.rust-lang.org/ {stable,nightly}
2: https://www.rust-lang.org/documentation.html
Maybe we could redirect 1, which is out of date, to 2?

**Comment by steveklabnik** [comment]
1 is out of date?

**Comment by liigo** [comment]
'Copyright © 2011-2015' and 'Copyright © 2011' in 1.
1 has much less contents than 2.
Maybe 2 could replace 1. Is there any reason to have two similar pages?

**Comment by brson** [comment]
The reasons they are separate are mostly technical. docs.rust-lang.org is a pass-through to the documentation s3 bucket and generated from the Rust source tree, separately from the website. That page, when considered independently from the website, like on your hard disk, serves as an index to the Rust docs we distribute. On the internet it is redundant by the website docs index.

We could redirect doc.rust-lang.org or make it just display the same thing as the website doc page. Would be good to do something useful at the top level of that domain.

**Comment by liigo** [comment]
Yeah, so closing this.

**Comment by liigo** [comment]
Maybe I should not close this? I don't known.
