### ISSUE TITLE
Beta channel updates: FAQ and Downloads contradict

### ISSUE THREAD

**Issue by 0joshuaolson1** [rust-lang/rust-www#418]
FAQ: [site](https://www.rust-lang.org/faq.html#how-does-rust-language-versioning-work), [source](https://github.com/rust-lang/rust-www/blob/master/faq.md#how-does-rust-language-versioning-work) - "updated every six weeks"

Downloads: [site](https://www.rust-lang.org/downloads.html), [source](https://github.com/rust-lang/rust-www/blob/master/downloads.html) - "updated as needed"

Possibly relevant discussion about the release process: https://github.com/rust-lang/rust/pull/33009

**Comment by brson** [comment]
Yeah it's worded inaccurately in the FAQ. Beta actually is updated every six weeks at the time channels are promoted, but between stable releases its also updated as needed. Clarification would be welcome.
