### ISSUE TITLE
Improve documentation search

### ISSUE THREAD

**Issue by 0joshuaolson1** [rust-lang/rust-www#420]
I'd love to see better searching. Besides

1. the lack of search for the book itself,
2. search filters out some characters without telling you, e.g. `C++` and `[Unstable]` are reasonable search terms, but the first gives false positives by using `C` and the second isn't indexed?

Related: the [search box](http://doc.rust-lang.org/nightly/std/) says that `?` gives more options, but it just lists everything like a wildcard.

**Comment by steveklabnik** [comment]
This repo is for the website, but the stuff that makes all of this is in the main repo. I believe that all of it has open issues already, but can't look right now.

**Comment by 0joshuaolson1** [comment]
Sorry, I just couldn't find it.

**Comment by steveklabnik** [comment]
It's all good! lots of repositories is tough. Generally, anything under
doc.rust-lang.org is generated by the main repo, only the main site itself
is here.
