### ISSUE TITLE
New Website Logo: Postmates

### ISSUE THREAD

**Issue by blt** [rust-lang/rust-www#425]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: Postmates
- Homepage url: https://postmates.com/
- Logo url: ![postmates-logo-black-500x500](https://cloud.githubusercontent.com/assets/3579/16534042/bdffe01c-3f91-11e6-838a-f95dfae7173e.png)
- How you are using Rust: Rust is being incubated in the Infrastructure team to write system daemons. 
- Url describing Rust usage: n/a yet 
- Organization contact: Brian L. Troutwine <blt@postmates.com>

**Comment by steveklabnik** [comment]
Thanks so much @blt ! @brson and I just merged it in :D

**Comment by blt** [comment]
:D
