### ISSUE TITLE
Fix friends of rust website  https://www.rust-lang.org/en-US/friends.html

### ISSUE THREAD

**Issue by abhi12ravi** [rust-lang/rust-www#437]
When I navigate from https://www.rust-lang.org/en-US/faq.html to https://www.rust-lang.org/en-US/friends.html - the link seems to be broken.
The same URL has been used in quite a few projects.

Specific focus:

 `<a href="friends.html">A growing number of organizations!</a>`

**Comment by alexcrichton** [comment]
cc @steveklabnik
