### ISSUE TITLE
Internal Website Error on Rust security policy page

### ISSUE THREAD

**Issue by Olathe** [rust-lang/rust-www#442]
The ["Rust security policy"](https://www.rust-lang.org/en-US/security.html) link on the ["Rust Documentation"](https://www.rust-lang.org/en-US/documentation.html) page leads to a page that says there's an `Internal Website Error`.

Timestamp: `<!-- Page last generated 2016-07-11 22:50:41 +0000 -->`

**Comment by alexcrichton** [comment]
Thanks for the report!
