### ISSUE TITLE
Media / Press Kit page

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-www#45]
With logos that people can use in articles, and what license they're under, blurbs about Rust, etc.

https://www.python.org/community/logos/ is an example, as is https://www.ruby-lang.org/en/about/logo/

See also https://github.com/rust-lang/rust/issues/11562, though I see this as being slightly broader and also, a ticket to actually implement the page.

**Comment by aldeka** [comment]
Just a note that this is something I am currently working on!

**Comment by steveklabnik** [comment]
:confetti_ball:

**Comment by AndrewBrinker** [comment]
Any progress here? It would be nice to have clear rules about the use of the Rust logo, and some standard art for the language.

**Comment by steveklabnik** [comment]
We're very close to having guidlines about usage for the logo, but legal stuff takes time. Soon.

**Comment by AndrewBrinker** [comment]
Good to hear!

**Comment by caipre** [comment]
Landed here after a search. The link to https://github.com/rust-lang/rust/issues/11562 above points to https://www.rust-lang.org/en-US/legal.html, which seems like it applies here as well.

@steveklabnik close?

**Comment by steveklabnik** [comment]
Yes, let's close this one. Thanks.
