### ISSUE TITLE
Emails on Teams page is invalid

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust-www#459]
The email links on the teams.md page show eg. `mailto:rust-mods [at] rust-lang [dot] org` and are invalid.

I tried to fix this, but I'm not sure what's adding the link. There's no actual link in the team.md for the link.

**Comment by steveklabnik** [comment]
I believe this is an intentional anti-spam measure. I'd be in favor of just changing it to an email. 

It's in the YAML block at the top of https://raw.githubusercontent.com/rust-lang/rust-www/8c30aeb0be86dcc8b405f79f737a008209b05cb5/en-US/team.md

**Comment by brson** [comment]
Fixed.
