### ISSUE TITLE
"Our public key" link is broken on the Rust Security Policy page

### ISSUE THREAD

**Issue by mkrautz** [rust-lang/rust-www#466]
https://www.rust-lang.org/en-US/security.html

The link to "[...]. If you would like, you can encrypt your report using [our public key](https://www.rust-lang.org/en-US/rust-security-team-key.gpg.ascii)." is broken:

https://www.rust-lang.org/en-US/rust-security-team-key.gpg.ascii

**Comment by steveklabnik** [comment]
Ah ha, thanks! The actual link is https://www.rust-lang.org/rust-security-team-key.gpg.ascii

now to fix it...

**Comment by mkrautz** [comment]
Don't worry! It wasn't because I had any security issues to report. :-)

**Comment by steveklabnik** [comment]
I was in fact wondering :sweat_smile:
