### ISSUE TITLE
Recommend rustup.rs over rustup.sh

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust-www#478]
Specifically at https://www.rust-lang.org/en-US/downloads.html, and recommend rustup.rs for Windows too, right?

We've [switched the new book to do this already](https://github.com/rust-lang/book/commit/8af84e7514be2a3aa72e3a421925cf68cb73f342) :)

If it's too soon to do this because rustup.rs isn't stable enough yet, consider this a reminder issue to make this change once it is :)

**Comment by steveklabnik** [comment]
@brson wants to wait another release cycle or two. And we'd need to update the current book as well.

**Comment by brson** [comment]
I'm very reluctant to do so without resolve this: https://github.com/rust-lang-nursery/rustup.rs/issues/524

**Comment by alexcrichton** [comment]
Done!

🎆
