### ISSUE TITLE
Errors displayed after running front-page code look bad

### ISSUE THREAD

**Issue by brson** [rust-lang/rust-www#490]
They are not in an equal width font and have no colors.

**Comment by brson** [comment]
Probably the simplest fix is to turn these into preformatted text.

**Comment by SergioBenitez** [comment]
I originally wrote the [error parsing function](https://github.com/rust-lang/rust-www/blob/master/_includes/editor.js#L222-L235) which formatted errors nicely and highlighted them in the editor, but the new error format means that this function no longer works. Furthermore, the new error format isn't easily parseable.

I think the best strategy would be to have a way for the playpen to return JSON formatted error messages from `rustc`. Perhaps the playpen can accept an additional `error_format` option with two values: `"text"`, or `"json"`. Then, we can use the JSON format on the main page and the text format in the web UI to reimplement the error parsing function.

**Comment by SergioBenitez** [comment]
In the meantime, I submitted https://github.com/rust-lang/rust-www/pull/510 which uses the same approach as before for the new error format.
