### ISSUE TITLE
Missing error codes

### ISSUE THREAD

**Issue by adelarsq** [rust-lang/rust-www#495]
On the page [Rust Compiler Error Index](https://doc.rust-lang.org/error-index.html) error codes that are bigger than E0522 are missing.

**Comment by steveklabnik** [comment]
Sorry you've been bouncing around repos; this is fundamentally a lack in the compiler itself, not the website. All errors have codes, but not all errors have longer explanations yet. This ticket is fundamentally a duplicate of https://github.com/rust-lang/rust/issues/32777

Thanks for filing!

**Comment by adelarsq** [comment]
Got it. Thanks @steveklabnik
