### ISSUE TITLE
Firefox 30, Chromium Version 36.0.1985.125 (283153), and Gnome Web on Archlinux. Text/Fonts are not showing up.

### ISSUE THREAD

**Issue by arslan** [rust-lang/rust-www#51]
www.rust-lang.org is not rendering properly. Text is not visible. Here are several screenshots with more information.
![rust2](https://cloud.githubusercontent.com/assets/2752218/3660337/bba9d5da-11b6-11e4-947a-561308a8d946.png)
![rust3](https://cloud.githubusercontent.com/assets/2752218/3660338/bbacad78-11b6-11e4-8085-2340dce6adb8.png)
![rust_lang](https://cloud.githubusercontent.com/assets/2752218/3660339/bbd2c22e-11b6-11e4-82f2-9f524f0f3617.png)

**Comment by gtirloni** [comment]
I just faced this issue on Fedora 23 with Firefox / Chrome after installing all Google Fonts (including Fira  Sans/Mono). After I deleted the fonts from my system, the website rendered correctly.
