### ISSUE TITLE
New Website Logo: Canonical

### ISSUE THREAD

**Issue by ChrisMacNaughton** [rust-lang/rust-www#518]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: Canonical
- Homepage url: https://www.canonical.com
- Logo url: https://upload.wikimedia.org/wikipedia/commons/1/15/Canonical_logo.svg
- How you are using Rust: Everything from server monitoring to middleware!
- Url describing Rust usage: 
- Organization contact: Chris MacNaughton <chris.macnaughton@canonical.com>

**Comment by brson** [comment]
Thanks @ChrisMacNaughton ! Sorry it's taken so long to get to this. I'll get it up asap.
