### ISSUE TITLE
Russian version of FAQ looks awkward

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/rust-www#527]
https://www.rust-lang.org/ru-RU/faq.html

![1](https://cloud.githubusercontent.com/assets/393741/18598265/9883552a-7c5a-11e6-86b2-895180ffb15e.PNG)

I don't remember we did anything with layout of this specific page, so not quite sure how to fix.

**Comment by steveklabnik** [comment]
Well, it, uh. Has no content https://github.com/rust-lang/rust-www/blob/master/ru-RU/faq.md
