### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by castillobgr** [rust-lang/rust-www#530]
¡Hola!

I'll start translating the website into Español (`es`) :)
I'll try my best to keep it neutral, so if anyone wants to join me and review each other's work that'd be great!

**Comment by castillobgr** [comment]
I hope to submit a PR for the finished (first) version of the Spanish translation next week. Man, that FAQ is long! :joy:

**Comment by castillobgr** [comment]
Sorry, I won't be able to continue with this. If anyone's interested, here's my fork with the progress I'd made: https://github.com/castillobgr/rust-www

**Comment by fylux** [comment]
@castillobgr Which parts are not translated or not fully translated?

**Comment by castillobgr** [comment]
@fylux everything translated is in the various es/ folders, named the same as their EN counterparts. Sorry for the delay, this notification got buried in my emails :/
