### ISSUE TITLE
New Website Logo: Ceph

### ISSUE THREAD

**Issue by scuttlemonkey** [rust-lang/rust-www#543]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: Ceph Community
- Homepage url: http://ceph.com
- Logo url: https://www.dropbox.com/s/snmtnvyaeioh5hc/Ceph_Logo_Stacked_RGB_120411_fa.ai?dl=0
- How you are using Rust: Rust bindings for librbd interface into Ceph storage platform.
- Url describing Rust usage: https://github.com/ceph/ceph-rust
- Organization contact: Patrick McGarry <pmcgarry@redhat.com>

**Comment by steveklabnik** [comment]
Thank you!
