### ISSUE TITLE
New Website Logo: Spoqa

### ISSUE THREAD

**Issue by segfault87** [rust-lang/rust-www#546]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

Organization name: Spoqa
Homepage url: https://www.spoqa.com (in Korean)
Logo url: https://s3.amazonaws.com/spoqa-website/static/img/spoqa_logotype_rgb_color_400px.png
How you are using Rust: Our POS integration SDK is entirely written in Rust.
Url describing Rust usage:
Organization contact: Eunchong Yu gracie@spoqa.com

**Comment by kmcallister** [comment]
I can add this one.
