### ISSUE TITLE
New Website Logo: LINE

### ISSUE THREAD

**Issue by freakhill** [rust-lang/rust-www#565]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: LINE
- Homepage url: https://line.me/
- Logo url: https://i.gyazo.com/a0947250a466b200c9f33d6b9c67701a.png
- How you are using Rust: configuration agent
- Url describing Rust usage: 
- Organization contact: gall.johan@linecorp.com

**Comment by freakhill** [comment]
transparent background png: http://livedoor.blogimg.jp/line_hr/imgs/c/b/cb68fe4b.png

**Comment by brson** [comment]
Merged. Thanks!
