### ISSUE TITLE
Mention Cargo on rust-lang.org/install.html

### ISSUE THREAD

**Issue by ajnirp** [rust-lang/rust-www#57]
(migrated from https://github.com/rust-lang/rust/issues/16798)

Users looking to download Rust binaries could be prompted to install Cargo alongside Rust if they want a package manager as well.

I wanted to do the [Piston tutorial](https://github.com/PistonDevelopers/Piston-Tutorials/tree/master/getting-started), so I downloaded the standalone Rust binaries from www.rust-lang.org/install.html, then realised that to get Cargo I'd have to do do `curl https://static.rust-lang.org/rustup.sh | sudo bash` which anyway fetches rustc binaries.

Maybe we could have a note on www.rust-lang.org/install.html saying "if you want a package manager, use the `rustup.sh` method"?

**Comment by xen0n** [comment]
Triage: fixed, now that [rustup.rs](https://rustup.rs) is the recommended way to install Rust, also featured on the homepage, which does install Cargo.

**Comment by steveklabnik** [comment]
Thanks @xen0n !
