### ISSUE TITLE
New Website Logo: craft ai

### ISSUE THREAD

**Issue by cloderic** [rust-lang/rust-www#570]
- Organization name: craft ai
- Homepage url: http://craft.ai
- Logo url: <http://www.craft.ai/media/craft_ai_square_logo.png> / <http://www.craft.ai/media/craft_ai_square_logo_small.png>
- How you are using Rust: craft ai is a machine learning API enabling developers to create services that adapt to each user - the core engine is written in Rust
- Organization contact: <contact@craft.ai>

**Comment by steveklabnik** [comment]
Thank you!
