### ISSUE TITLE
Give Links to pgp signature files on Download page

### ISSUE THREAD

**Issue by vishnunaini** [rust-lang/rust-www#594]
Currently the pgp signatures for files downloadable from the official download page are only obtainable by guessing the link by adding .asc to the actual files' download link

i.e guessing https://static.rust-lang.org/dist/rust-1.12.1-x86_64-pc-windows-msvc.msi.asc for https://static.rust-lang.org/dist/rust-1.12.1-x86_64-pc-windows-msvc.msi 

It would be better if these asc files are prominently linked on the download page. 

Edit: Also link the official signing key on the download page

**Comment by alexcrichton** [comment]
This is now done, so closing

https://www.rust-lang.org/en-US/other-installers.html
