### ISSUE TITLE
New Website Logo: Clever Cloud

### ISSUE THREAD

**Issue by Geal** [rust-lang/rust-www#603]
- Organization name: Clever Cloud
- Homepage url: https://www.clever-cloud.com/
- Logo url: http://dev.unhandledexpression.com/clever-svg.svg
- How you are using Rust: we host Rust web apps (currently in beta), and a part of our infrastructure (around git and app management) is developed in Rust
- Url describing Rust usage: https://www.clever-cloud.com/doc/rust/rust/
- Organization contact: Geoffroy Couprie geoffroy.couprie@clever-cloud.com

**Comment by steveklabnik** [comment]
Sorry about taking so long with the PR! I was out of town.

**Comment by Geal** [comment]
I was out of town too ;)
