### ISSUE TITLE
Weibo, Please！

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/rust-www#608]
It's not easy to log rn to sites like YouTube,  Twitter and Google in China. We need a official Weibo to get news for Rust language. Even if it reported by English.

**Comment by steveklabnik** [comment]
This issue isn't likely to be the right spot to talk about this, as few people follow this repository. Maybe @rust-community/community-team has ideas?

**Comment by steveklabnik** [comment]
gah, looks like that doesn't @ mention them.
