### ISSUE TITLE
curl | sh, Wall of Shame

### ISSUE THREAD

**Issue by mrmiywj** [rust-lang/rust-www#609]
We are on the [Wall of Shame](https://gnu.moe/wallofshame.md)!

**Comment by arrowrowe** [comment]
> [Rust](https://www.rust-lang.org/downloads.html)  
> > curl -sSf https://static.rust-lang.org/rustup.sh | sh
> 
> Holy shit. Even Rust is run by retards.
>

from _[Wall of Shame](https://gnu.moe/wallofshame.md)_

**Comment by hoodie** [comment]
The language on this site is from an era before we had COCs I suppose.
Still, I don't like the concept of `wget some.site | bash` either, but I can't come up with something better, other than having people download and manually execute the script.

**Comment by BurntSushi** [comment]
**Moderator note**: While we love to receive criticism, we'd appreciate it if it were constructive. Please see our [Code of Conduct](https://www.rust-lang.org/en-US/conduct.html) for what is appropriate and what's not. If you have any questions, please contacts us at rust-mods@rust-lang.org.

**Comment by steveklabnik** [comment]
Closing and locking on @BurntSushi 's behalf, since I happen to have access, and he does not.
