### ISSUE TITLE
Links in English version do not specify en-US which prevents user from switching to English from other language

### ISSUE THREAD

**Issue by yeputons** [rust-lang/rust-www#619]
Strictly speaking, the following happens:
1. I navigate to <a href="https://www.rust-lang.org">www.rust-lang.org</a> and get instantly redirected to <a href="https://www.rust-lang.org/ru-RU/">www.rust-lang.org/ru-RU</a> (probably because my browser knows my default language).
2. I click on "English" in the footer, it takes me to <a href="https://www.rust-lang.org/en-US/">www.rust-lang.org/en-US/</a>, which is displayed in English.
3. But if I then click on "Documentation" in the English version, it takes me to <a href="https://www.rust-lang.org/documentation.html">www.rust-lang.org/documentation.html</a>, and from there I get instantly redirected to the Russian version: <a href="https://www.rust-lang.org/ru-RU/documentation.html">www.rust-lang.org/ru-RU/documentation.html</a>.
4. If I manually change `ru-RU` to `en-US` in the link, I see English version of documentation. However, all header links from <a href="https://www.rust-lang.org/en-US/documentation.html">www.rust-lang.org/en-US/documentation.html</a> still do not include `en-US` in the URL.

I believe this issue is slightly related to #618 .

**Comment by steveklabnik** [comment]
Yeah this is a hard problem....

**Comment by 3442853561** [comment]
I have just fixed this problem. #624

**Comment by yeputons** [comment]
Fixed by @3442853561  in #624 and I can confirm that the issue is resolved.
