### ISSUE TITLE
static.rust-lang.org: Suggestion of deleting redundant files

### ISSUE THREAD

**Issue by mzji** [rust-lang/rust-www#630]
All files end with these extensions seem redundant:
```
.tar.gz.asc.asc
.tar.gz.asc.asc.sha256
.tar.gz.asc.asc.sha256.sha256
.tar.gz.asc.sha256.sha256
.tar.gz.sha256.sha256
```
All of them created at the same time (2016-01-11 09:30/09:31), looks like they are generated by accident.
Should we delete them? That will make file list cleaner.

**Comment by alexcrichton** [comment]
These are historical, and we generally don't delete files, but we've since fixed the bug that caused these to get generated.
