### ISSUE TITLE
Timeout Triggered

### ISSUE THREAD

**Issue by warent** [rust-lang/rust-www#632]
Hi there,

I just came by to take a look at what all the fuss of Rust is about. I saw the website had a "Try Rust" thing which was nice. All I did was hit "Run" and it didn't seem to work. Is this expected behavior? Kind of off-putting
![screenshot from 2016-12-06 19-54-09](https://cloud.githubusercontent.com/assets/13342266/20953037/d5fde690-bbed-11e6-8583-2df029d44e93.png)

**Comment by steveklabnik** [comment]
So, this does run code dynamically, so if the playpen is down, this can happen. /cc @alexcrichton

**Comment by alexcrichton** [comment]
Ah yeah this is just an intermittent error, so closing.
