### ISSUE TITLE
NetBSD is not recognized.

### ISSUE THREAD

**Issue by iquiw** [rust-lang/rust-www#639]
"I don't recognize your platform." message is displayed on [Installation page](https://www.rust-lang.org/en-US/install.html)

Here is the values the page shows.

```
navigator.platform:
NetBSD amd64
navigator.appVersion:
5.0 (X11)
```

I could install `rustup` and `rustc`, etc. by manually downloaded `rustup-init`.

**Comment by brson** [comment]
Thank you!
