### ISSUE TITLE
Minor nitpick in the Rust FAQ

### ISSUE THREAD

**Issue by nc-x** [rust-lang/rust-www#657]
Here,
  
https://www.rust-lang.org/en-US/faq.html#why-do-rust-programs-use-more-memory-than-c
  
Instead of "memory", "disk storage" or something along those lines seems more suitable.

**Comment by AndrewBrinker** [comment]
Yeah, this seems like a legitimate nit. As I recall, the name of the question came from the phrasing used by the person who suggested the question. But changing it seems good. Want to make the PR?

**Comment by nc-x** [comment]
@AndrewBrinker Opened the PR.
