### ISSUE TITLE
No option to select installation platform to show instructions

### ISSUE THREAD

**Issue by barrkel** [rust-lang/rust-www#663]
I'm trying to install rustc on a headless Ubuntu 14.04 box, and I browsed to https://www.rust-lang.org/en-US/install.html to look for instructions. But the instructions are all for Windows, the platform my browser was running under.

The instructions for Linux aren't visible without viewing the source code of the web page.

**Comment by steveklabnik** [comment]
If you click on "Other installation methods" at the bottom of the page, it shows all platforms on one page.

**Comment by barrkel** [comment]
Indeed. It wasn't clear whether that was going to lead to an unorthodox installation technique.

What's not clear is how to install to somewhere other than my home directory - I don't want to have to install multiple copies for different users, and my home directory is encrypted, it's not even mounted depending on how I log in. But it's a separate issue.
