### ISSUE TITLE
‘Run’ button on home page stopped working

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rust-www#687]
The run button on the [home page](https://www.rust-lang.org/en-US/) stopped working.

The output window reports:
```
rustc 1.15.0-beta.3 (a035041ba 2017-01-07)

timeout triggered!
```

A minor issue, but important from a PR standpoint.

**Comment by steveklabnik** [comment]
Still seeing this now. I wonder why it's trying to run on a beta?

**Comment by Havvy** [comment]
This is still happening.

**Comment by steveklabnik** [comment]
@alexcrichton do you know what's up here? this seems bad :(

**Comment by alexcrichton** [comment]
This is just an intermittent error, should be fixed now
