### ISSUE TITLE
New Website Logo: Wire

### ISSUE THREAD

**Issue by teller** [rust-lang/rust-www#704]
- Organization name: Wire
- Homepage url: https://wire.com
- Logo url: https://www.dropbox.com/s/h6bldfpmohmkkvb/Wire%20logo.svg?dl=0
- How you are using Rust: Wire's Axolotl protocol implementation and other cryptographic and utility libraries are developed in Rust, then cross-compiled for iOS and Android. 
- Url describing Rust usage: https://github.com/wireapp/proteus
- Organization contact: Siim Teller, siim@wire.com

**Comment by 3442853561** [comment]
I forgot to add Url describing Rust usage.
I am sorry for my mistakes.
@teller @brson
