### ISSUE TITLE
New mozilla logo

### ISSUE THREAD

**Issue by est31** [rust-lang/rust-www#715]
[Mozilla has a new logo](https://blog.mozilla.org/opendesign/arrival/).

The old one is still used on https://www.rust-lang.org/en-US/friends.html

**Comment by LLBlumire** [comment]
Just went to write a pull request for this,

It appears mozilla has yet to adopt the style in their style guide.

https://www.mozilla.org/en-US/styleguide/identity/mozilla/branding/

This might be deliberate or an oversite, but before it is added there I don't know where we would go about getting an acurate logo to use. Possibly the correct thing to do is wait for them to update this page, and role their branding out everywhere, then update it?

**Comment by bstrie** [comment]
@LLBlumire That page appears to have been updated.

**Comment by ranjithrajvasam** [comment]
It can be edited here https://github.com/rust-lang/rust-www/tree/master/user-logos
