### ISSUE TITLE
"Install Rust" version number out of date on French site

### ISSUE THREAD

**Issue by chrish42** [rust-lang/rust-www#725]
On the French version of the website, the blue "Install Rust" button talks about Rust 1.14.0, while the latest version (and the one on the English version of the site) is 1.5.1.

**Comment by 3442853561** [comment]
As far as I see the result, it is already 1.15.1. You may not have to clear the browser's cache.

**Comment by chrish42** [comment]
Actually, https://rust-lang.org/fr-FR/ shows 1.51.1. But https://rust-lang.org/fr/ (to which https://rust-lang.org/ automatically redirects for me) shows 1.14.0.

**Comment by 3442853561** [comment]
https://rust-lang.org/fr/  This page is no longer available. So I think it might be your browser's cache.

**Comment by chrish42** [comment]
Hmm. Add "www" to all this links. So `curl https://www.rust-lang.org/fr/|fgrep 1.14` shows the problem.

**Comment by 3442853561** [comment]
I'm try to fix it. https://github.com/rust-lang/rust-www/pull/743

**Comment by 0xpr03** [comment]
Resolved ?

**Comment by chrish42** [comment]
Welll, the links that used to lead to a wrong version are now 404, etc., and the one link to the French version of the website displays the latest version. So, looks like it's fixed to me.
