### ISSUE TITLE
New Website Logo: CodePicnic

### ISSUE THREAD

**Issue by alvaropereyra** [rust-lang/rust-www#729]
- Organization name: CodePicnic
- Homepage url: https://codepicnic.com
- Logo url: https://codepicnic.com/basket.png
- How you are using Rust: We provide Rust sandboxes people can play around with, as well as fork to expand examples and apps they want to.
- Url describing Rust usage: https://codepicnic.com/posts/console-of-the-day-rust-f7664060cc52bc6f3d620bcedc94a4b6/?utm_source=twitter&utm_medium=blog&utm_term=codepicnic+rust&utm_campaign=codepicnic_features_201702
- Organization contact: Alvaro Pereyra Rabanal (alvaro@codepicnic.com)

**Comment by 3442853561** [comment]
I will help you.

**Comment by Boereck** [comment]
It looks like the website is down and there is no recent sign this company is operating anymore.
