### ISSUE TITLE
Accessing the website from France: wrong redirection

### ISSUE THREAD

**Issue by Insomgla** [rust-lang/rust-www#742]
Linked to #725 

If I browse to this address : `https://www.rust-lang.org/`, I'm getting redirected to `https://www.rust-lang.org/fr/`, instead of `https://www.rust-lang.org/fr-FR/`.

There are 2 notable problems with this : 

- The blue button features Rust 1.14

- The translation of 1 of the menu item ("Install") is not correct, the translation on the `fr-FR` version is right

**Comment by 3442853561** [comment]
I'm try to fix it. https://github.com/rust-lang/rust-www/pull/743

**Comment by Insomgla** [comment]
Thanks!

**Comment by MI53RE** [comment]
Hello, did meet the redirect problem today too through google (with fr and es), was the fix not yet pushed or was there a rollback? (just asking!)

**Comment by steveklabnik** [comment]
@brson @alexcrichton I think we might need to delete some files off of the S3 bucket; any ideas?

**Comment by alexcrichton** [comment]
Sure yeah we can do that, what files need to be deleted?

**Comment by steveklabnik** [comment]
Everything in `/fr` and `/es`; `/fr-FR` and `/es-ES` should exist instead.

**Comment by alexcrichton** [comment]
Ok I've deleted those folders and issued an invalidation for `/*`, may take a few minutes to show up

**Comment by steveklabnik** [comment]
Looks like it's gone now!

**Comment by MI53RE** [comment]
Thanks =)!
