### ISSUE TITLE
New Website Logo: ETCDEV Team

### ISSUE THREAD

**Issue by splix** [rust-lang/rust-www#748]
- Organization name: ETCDEV Team
- Homepage url: https://www.etcdevteam.com/
- Logo url: https://www.etcdevteam.com/images/etcface_nobg.png
- How you are using Rust: ETCDEV Team is a group of professional software engineers working full time on Ethereum Classic core projects
- Url describing Rust usage: (that's good idea, will make a post in our blog later)
- Organization contact: Igor Artamonov splix@etcdevteam.com

**Comment by steveklabnik** [comment]
> (that's good idea, will make a post in our blog later)

Great! We can link to that later, let us know when that happens. 

In the meantime, PR sent to add you 😄
