### ISSUE TITLE
rust-lang.org is not rendering correctly (blank)

### ISSUE THREAD

**Issue by ldng** [rust-lang/rust-www#75]
Most of rust-lang.org is not rendering correctly for me.
Neither with Firefox 34.0.5 nor with Chromium 39.0.2171.95 on Archlinux.
Firefox's console does not show any error but  Chrome's one tell me :
        Resource interpreted as Font but transferred with MIME type binary/octet-stream: "http://doc.rust-lang.org/Heuristica-Italic.woff"
The MIME type in Firefox is "application/x-font-woff" so I'm not sure it is the issue here.

![core - rust](https://cloud.githubusercontent.com/assets/781064/5428818/16177cc8-83d3-11e4-8198-0e95ed24febb.png)

**Comment by skade** [comment]
Just wanted to put here: if you experience the problem, the current official Arch packages for Fira Sans should work.

https://www.archlinux.org/packages/community/any/ttf-fira-sans/
