### ISSUE TITLE
More Welcoming Snippet In Rust's Home Page

### ISSUE THREAD

**Issue by tebanep** [rust-lang/rust-www#754]
This is issue is a suggestion for improving the first impression a person gets with Rustlang. I think the code example displayed in https://www.rust-lang.org should be simpler and smaller. After actually using Rust, I noticed that it was way easier than I expected coming from Python. It wasn't obvious at first sight though. So my recommendation is to put a more welcoming snippet in the home page, so that people get motivated to try out the language!

This is the first Rustlang code many people see (at least it was in my case): 

// This code is editable and runnable!
fn main() {
    // A simple integer calculator:
    // `+` or `-` means add or subtract by 1
    // `*` or `/` means multiply or divide by 2

    let program = "+ + * - /";
    let mut accumulator = 0;

    for token in program.chars() {
        match token {
            '+' => accumulator += 1,
            '-' => accumulator -= 1,
            '*' => accumulator *= 2,
            '/' => accumulator /= 2,
            _ => { /* ignore everything else */ }
        }
    }

    println!("The program \"{}\" calculates the value {}",
              program, accumulator);
}

Compare it to that of Go's: (https://golang.org)

// You can edit this code!
// Click here and start typing.
package main

import "fmt"

func main() {
	fmt.Println("Hello, 世界")
}

Or Python's: (https://www.python.org)

\# For loop on a list
>>> numbers = [2, 4, 6, 8]
>>> product = 1
>>> for number in numbers:
...    product = product * number
... 
>>> print('The product is:', product)
The product is: 384

Thanks for making Rust. It is an awesome language that I hope I will be able to partner with Python for CPU expensive tasks!

**Comment by 3442853561** [comment]
This is a wonderful and exciting idea.
This is some of my advice.
Print "hello" in each language.
In order to show Rust's friendly and inclusive.
```
fn main() {
    println!("Hello");
    println!("こんにちは");
    println!("您好");
}
```

**Comment by tebanep** [comment]
Right! One thing I've noticed with Rust is that the website is translated to several languages (including spanish). Neither Python or Go has that. This makes Rust look much more inclusive and diverse regarding its community!

**Comment by brson** [comment]
This is done. Thanks @tebanep !

**Comment by tebanep** [comment]
Thanks @brson for taking our suggestion into account! Hope it helps in making Rust more appealing for newcomers!
