### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by madieraRRC** [rust-lang/rust-www#762]

**Comment by madieraRRC** [comment]
$./x.pybuild&&sud-ouest. x.pydist__install

**Comment by steveklabnik** [comment]
@madieraRRC this is the repository for the website, not rust itself. Could you please file this bug over here: http://github.com/rust-lang/rust/issues/new

also, we need the output of that command if we're able to help; "does not install" doesn't say what went wrong. Thanks!
