### ISSUE TITLE
404 page on static.rust-lang.org cannot find assets

### ISSUE THREAD

**Issue by postmodern** [rust-lang/rust-www#77]
The [404 page](https://static.rust-lang.org/lolnope) on `https://static.rust-lang.org` is attempting to load assets via relative URLs, instead of directly from `http://www.rust-lang.org`.

**Comment by zarvox** [comment]
While the assets links appear to specify the host now, it looks like they should also be protocol-relative links (e.g. `<img src="//www.rust-lang.org/logos/rust-logo-32x32-blk.png">`) lest you get mixed-content failures when viewing over HTTPS.

**Comment by zarvox** [comment]
This appears to have been fixed by rust-lang/rust@bbbfed2f93d3ba58a53ed8bf353ed11f3bb751db

**Comment by alexcrichton** [comment]
Yay!
