### ISSUE TITLE
New Website Logo: krypt.co

### ISSUE THREAD

**Issue by kcking** [rust-lang/rust-www#791]
- Organization name: krypt.co
- Homepage url: https://krypt.co
- Logo url: https://imgur.com/a/pl3BM
- How you are using Rust: Shared code between iOS and Android for [SSH host signature verification](https://github.com/kryptco/ssh-wire) as well as a [PKCS11 shared library](https://github.com/KryptCo/kr/tree/master/pkcs11shim).
- Organization contact: kevin@krypt.co

**Comment by 3442853561** [comment]
I will help you.
