### ISSUE TITLE
New Website Logo: superscale networks

### ISSUE THREAD

**Issue by aep** [rust-lang/rust-www#799]
- Organization name: superscale networks
- Homepage url: https://www.superscale.io | https://github.com/superscale
- Logo url: https://s3-eu-west-1.amazonaws.com/www.superscale.io/logo.svg or https://www.superscale.io/logo.svg
- How you are using Rust: We run rust-mips on tens of thousands of linux routers with 4-16Mb Ram. Rust is the only modern language that has low enough runtime constrains to make this possible.
- Organization contact: aep@hy5.berlin

**Comment by Boereck** [comment]
@aep is superscale.io still a thing? The web page seems down. Should this logo be removed or replaced?

**Comment by aep** [comment]
@Boereck yep. it should redirect to devguard.io. Looks like it doesnt, sorry.
Let me fix that when i'm back on wednesday.

**Comment by aep** [comment]
Sorry the redirect is taking longer than expected.
superscale has been merged into devguard, which is 100% rust now, not just embedded but also middleware and web. 

Could you replace the logo, as well as the url?

Homepage url: https://devguard.io
Logo url: ![dg-logo-dark](https://user-images.githubusercontent.com/136926/45553829-32ceef00-b835-11e8-8b41-d9ca7f24b7d2.png)

thank you!
