### ISSUE TITLE
'Run' new code fails (due to cross-domain issue?)

### ISSUE THREAD

**Issue by danthedeckie** [rust-lang/rust-www#81]
The 'run' button on the rust front page doesn't work for me (Firefox 34.0.5, OSX).  The status goes to 'running' and it just sits there.  If I open a javascript console, it says that:

    Cross-Origin Request Blocked:
        The Same Origin Policy disallows reading the remote resource at http://play.rust-lang.org/evaluate.json.
        This can be fixed by moving the resource to the same domain or enabling CORS.
            evaluate.json

    TypeError:
        message is null
            www.rust-lang.org:382

**Comment by robinst** [comment]
Same here, Firefox 35 on Fedora Linux (same with Epiphany). Leaves a bad impression currently, as if Rust was taking forever to run the program.

**Comment by alexcrichton** [comment]
I think this is fixed now, thanks for the report!
