### ISSUE TITLE
New Website Logo: VersionEye

### ISSUE THREAD

**Issue by reiz** [rust-lang/rust-www#816]
- Organization name: VersionEye
- Homepage url: https://www.versioneye.com/
- Logo url: https://www.versioneye.com/images/versioneye_logo.png
- How you are using Rust: We are using Rust to implement a command line tool which can identify software dependencies by their SHA values. 
- Url describing Rust usage: https://blog.versioneye.com/2017/04/27/shazam-for-software-libraries/
- Organization contact: Robert Reiz <reiz@versioneye.com>

**Comment by Boereck** [comment]
The VersionEye company seems to be shut down, see blog entry: https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
This entry should be removed.
