### ISSUE TITLE
New website logo: Structure Systems

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rust-www#839]
- Organization name: Structure Systems
- Homepage URL: https://www.structure.systems
- Logo URL: https://www.structure.systems/media/Logo-Structure-Systems.svg
- How you are using Rust: we develop software in Rust that helps organizations comply with information privacy/data protection rules.
- Organization contact: Sander Maijers <contact@structure.systems>

**Comment by steveklabnik** [comment]
Thanks! 😄
