### ISSUE TITLE
Duplicate entries in list of Implementors in standard library docs

### ISSUE THREAD

**Issue by mulkieran** [rust-lang/rust-www#840]
Go to: https://doc.rust-lang.org/std/ops/trait.Deref.html. Search in your browser for ```impl Deref for String```. Get two matches. Same for ```impl<T> Deref for Vec<T>```.

Also, look for ```Box```, ```Arc```, and ```Rc```. These each get three entries. Two are identical as strings, but the third is identical in meaning, AFAICT.

**Comment by mulkieran** [comment]
Also, it is quite unclear to me what order the implementors are displayed in...I suspect it is some kind of random artifact of the implementation.

**Comment by steveklabnik** [comment]
Can you file this bug against https://github.com/rust-lang/rust/ please? This is a bug in the doc generation tool, not in the website. Thank you!

**Comment by mulkieran** [comment]
Old issue: https://github.com/rust-lang/rust/issues/25061.
