### ISSUE TITLE
Inconsistancy in generated links for standard library docs

### ISSUE THREAD

**Issue by mulkieran** [rust-lang/rust-www#841]
Go to: https://doc.rust-lang.org/std/ops/trait.Index.html. Note that in some places ```usize``` is a link to documentation about usize, but in other places, ```usize``` gets no link.

**Comment by steveklabnik** [comment]
Can you re-file this at https://github.com/rust-lang/rust/ please? It's a bug in the doc generation tool, not on the website proper. Thank you!
