### ISSUE TITLE
New book on Rust published by Packt

### ISSUE THREAD

**Issue by packtpartner** [rust-lang/rust-www#846]
Hi,

Packt has published a new book on Rust last month.
[Mastering Rust](https://www.packtpub.com/application-development/mastering-rust) written by Vesa Kaihlavirta
The book contains a mix of theory interspersed with hands-on tasks, so you acquire the skills as well as the knowledge. Improving performance, using generics, building macros, and working with threads are just some of the topics we’ll cover. We’ll talk about the official toolsets and ways to discover more.

Can this book be featured on the [Documentation page](https://www.rust-lang.org/en-US/documentation.html) under Learning Rust?
I think it would be a good learning resource.

**Comment by packtpartner** [comment]
@carols10cents and @alexcrichton can you help me out?

**Comment by carols10cents** [comment]
Hi, I think we're only linking to official resources on this page. https://github.com/ctjhoa/rust-learning is where we gather all other resources!
