### ISSUE TITLE
Can I do l10n for the website and documentation?

### ISSUE THREAD

**Issue by caizixian** [rust-lang/rust-www#85]

**Comment by steveklabnik** [comment]
The site might be okay, but the documentation needs to be in some kind of finished state before we commit to doing a ton of i18n work. It's hard enough to keep it up to date in just English!

**Comment by caizixian** [comment]
@steveklabnik So I plan to do i18n for the site.
Is there any recommended way or tool to do this? (Or best practise?)

**Comment by caizixian** [comment]
@alexcrichton @steveklabnik @brson 
So I plan to do i18n for the site.
Is there any recommended way or tool to do this? (Or best practise?)

**Comment by caizixian** [comment]
Closed.
Move to rust-lang/rust#21129
