### ISSUE TITLE
FAQ: don't link to @aturon's style guides

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-www#856]
https://www.rust-lang.org/en-US/faq.html#design-patterns

https://aturon.github.io/ownership/builders.html should link to https://doc.rust-lang.org/stable/book/first-edition/method-syntax.html#builder-pattern instead

**Comment by ashleygwilliams** [comment]
Duplicate of #871 

(this is a test sorry)

**Comment by ashleygwilliams** [comment]
(sorry about the timeline note i was using this to demo to github that the mark duplicate feature has some issues)

**Comment by juleskers** [comment]
Since  #1022 was merged , I believe this can be closed, no?

ping @steveklabnik ?

**Comment by steveklabnik** [comment]
Yup!
