### ISSUE TITLE
New Website Logo: [WINK Streaming]

### ISSUE THREAD

**Issue by winkmichael** [rust-lang/rust-www#869]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: WINK Streaming
- Homepage url: www.winkstreaming.com
- Logo url: http://64.94.15.40/wink_logo.png
- How you are using Rust: Rust key to our core low latency H.264 and HEVC encoding and transcoding engine. 
- Url describing Rust usage: (optional link to e.g. blog post explaining how you use Rust)
- Organization contact: Michael McConnell - michael@winkstreaming.com

**Comment by 3442853561** [comment]
https://github.com/rust-lang/rust-www/pull/881
