### ISSUE TITLE
FAQ, "compilation seems slow", MIR

### ISSUE THREAD

**Issue by uvtc** [rust-lang/rust-www#884]
Hi, new here. At <https://www.rust-lang.org/en-US/faq.html#why-is-rustc-slow>, it mentions a hope of a future MIR optimization, but searching around it appears to me that MIR has already been merged. Has this optimization been implemented?

**Comment by AndrewBrinker** [comment]
Incremental compilation is unfinished, but is (if I recall correctly) available today on nightly.

I'm not sure if any serious work has gone into MIR-level optimizations to reduce the time spent in LLVM optimization.

I'll update the answer.
