### ISSUE TITLE
Install page is awkward for WSL users

### ISSUE THREAD

**Issue by hyperpape** [rust-lang/rust-www#889]
When I go to https://www.rust-lang.org/en-US/install.html as a windows 10 user, I see an install link for Windows 10, which is great. 

However, Windows 10 now has the Windows subsystem for linux, which many devs use, and which is where I'd like to install Rust. From the Windows install page, the linux install instructions are (afaik) only accessible from the "other installation methods" section. 

Would it make sense to either a) add a more obvious link to installations for other platforms for all install pages or b) add a subsection for WSL install instructions for Windows users? 

a) might have the advantage that it would work nicely for anyone whose user-agent is improperly handled.

**Comment by 0xpr03** [comment]
Would recommend a PR with a link to installation on linux when sb wants to use the subsystem.
