### ISSUE TITLE
link to 'getting started on windows' more prominently

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust-www#90]
originally filed as https://github.com/rust-lang/rust/issues/14146 by @SimonSapin

**Comment by EduardoBautista** [comment]
Doesn't seem to be an issue anymore according to the [wiki](https://github.com/rust-lang/rust/wiki/Using-Rust-on-Windows):

"As of release 0.12, Rust distribution for Windows is completely self-contained and includes all dependencies from MinGW toolchain required for building Windows binaries."
