### ISSUE TITLE
New Website Logo: CancerIQ

### ISSUE THREAD

**Issue by Ethan826** [rust-lang/rust-www#959]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: CancerIQ
- Homepage url: http://www.canceriq.com/
- Logo url: https://s3-us-west-2.amazonaws.com/assets.canceriq.com/institutions/canceriq-demo/images/logo/large.png
- How you are using Rust: CancerIQ provides the tools for genetic counselors, imaging centers, and other practitioners to run a cancer risk program; Rust powers several of our risk models.
- Url describing Rust usage: http://engineering.canceriq.com/posts/rust/
- Organization contact: ekent@canceriq.com

**Comment by alexcrichton** [comment]
Added in https://github.com/rust-lang/rust-www/pull/963, thanks!
