### ISSUE TITLE
New Website Logo: IamBot

### ISSUE THREAD

**Issue by riomus** [rust-lang/rust-www#961]
To list your organization's logo on the Rust website, fill out the following information and click "submit new issue". Alternately, you may edit _data/users.yml as described therein and submit a pull request.

- Organization name: IamBot
- Homepage url: http://iambot.ai
- Logo url: https://static1.squarespace.com/static/595f39b2b8a79b98defda753/t/59834c66d2b8576b8f9e6c17/1505988147175/?format=1500w
- How you are using Rust: Our high-performance data acquisition is fully implemented using Rust. Besides that, we are also using Rust for our API endpoints that communicate with internal systems. 
- Organization contact: r.bartusiak@iambot.ai

**Comment by riomus** [comment]
Unfortunately, I have given you fully white logo, and it is not visible on the webpage. Please change it to black version:  https://ibb.co/nvHjY6

**Comment by steveklabnik** [comment]
Done! Thanks :)
