### ISSUE TITLE
Make responsive layout for /book more responsive

### ISSUE THREAD

**Issue by Undeterminant** [rust-lang/rust-www#99]
I use a tiling window manager. My browser display width is 1042 pixels and I'm getting the mobile view because you require a 1060 pixel width. It'd make sense to use max-width instead of width on the body of the document so that you can drastically decrease the width requirement to display the sidebar.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rust#22682
