### ISSUE TITLE
Don't hide unix installation instructions

### ISSUE THREAD

**Issue by daveloyall** [rust-lang/rust-www#998]
Hello.

Look at these hidden "cycle through platform options" buttons: https://github.com/rust-lang/rust-www/search?q=platform-button

You should enable that button.   I could use it to find installation instructions for my GNU box.  I surf the web with my Windows box, but do my work in various unixen.

**Comment by steveklabnik** [comment]
At the bottom of https://www.rust-lang.org/en-US/install.html, there's an "other installation methods" section which links to https://www.rust-lang.org/en-US/other-installers.html, that contains all platforms on one page.

**Comment by daveloyall** [comment]
Ah, thanks.  I still don't like webpages that hide content.
